import type { CurriculumPack } from '../types.js';

export const cambridgeStage8English: CurriculumPack = {
  pack_id: 'cambridge-stage8-english',
  subject: 'English',
  stage_label: 'Cambridge Lower Secondary — Stage 8',
  strands: { reading: 'Reading', writing: 'Writing', grammar: 'Grammar & Mechanics', vocabulary: 'Vocabulary & Morphology' },
  nodes: [
    {
      id: 'reading-explicit-implicit', strand: 'reading', title: 'Explicit & Implicit Meaning',
      description: 'Distinguishing what a text states directly from what it suggests through detail and inference.',
      sample_passage: 'Maya set the letter on the table without opening it. She wiped her palms on her jeans twice, then a third time, and stared at the door until the kettle screamed.',
      order_index: 1,
      question: 'What is the passage telling you directly, and what is it letting you guess about how Maya feels?',
      misconception_triggers: ['just says she wiped her hands', 'no feelings mentioned', 'nothing implied'],
    },
    {
      id: 'reading-literary-techniques', strand: 'reading', title: 'Literary Techniques',
      description: 'Identifying metaphor, personification, and imagery, and explaining the effect each creates.',
      sample_passage: 'The old bridge groaned under every footstep, complaining like a tired giant who wanted nothing more than to lie down. Fog wrapped the valley in a grey blanket.',
      order_index: 2,
      question: 'Which words in this passage give something non-human a human quality, and what feeling does that create?',
      misconception_triggers: ['metaphor means comparing with like or as', 'simile and metaphor are the same', 'personification is just describing'],
    },
    {
      id: 'reading-tone-perspective', strand: 'reading', title: "Writer's Tone & Perspective",
      description: "Recognizing a writer's attitude toward their subject and whose point of view shapes the account.",
      sample_passage: 'Naturally, the council decided — without asking a single resident — that the park would become a car park. How wonderfully democratic of them.',
      order_index: 3,
      question: 'Do you think the writer approves of the council\'s decision? What in the wording makes you think that?',
      misconception_triggers: ['tone is just the topic', 'the writer sounds happy', 'perspective means the main character'],
    },
    {
      id: 'writing-narrative-structure', strand: 'writing', title: 'Narrative Structure',
      description: 'Shaping a story with deliberate stages: exposition, rising action, climax, resolution.',
      sample_passage: 'A short story that opens mid-argument, jumps back to explain how the argument started, then returns to resolve it, is using structure on purpose — not by accident.',
      order_index: 4,
      question: 'If a story started at its most exciting moment instead of the beginning, what would that choice do for the reader?',
      misconception_triggers: ['stories must go in time order', 'structure only means beginning middle end', 'climax is the same as the ending'],
    },
    {
      id: 'writing-persuasive-rhetoric', strand: 'writing', title: 'Persuasive Rhetoric',
      description: 'Using ethos, pathos, logos, and rhetorical questions to build a persuasive case.',
      sample_passage: 'As a lifelong volunteer at this shelter, I have held the paws of a hundred frightened animals. Is it really too much to ask for five minutes of your time?',
      order_index: 5,
      question: 'The writer mentions being a "lifelong volunteer" before asking anything — what kind of persuasion is that, and why put it first?',
      misconception_triggers: ['pathos means sad', 'ethos is just being honest', 'rhetorical questions always have obvious answers'],
    },
    {
      id: 'writing-register', strand: 'writing', title: 'Formal vs. Informal Register',
      description: 'Adjusting vocabulary, sentence length, and tone to suit an audience and purpose.',
      sample_passage: '"We regret to inform you that your application was unsuccessful." versus "Sorry, didn\'t work out this time — try again soon!"',
      order_index: 6,
      question: 'Both sentences say the same thing. What specific word or structural choices make the first one feel more formal?',
      misconception_triggers: ['formal just means longer words', 'informal means bad grammar', 'register is about the topic not the words'],
    },
    {
      id: 'grammar-complex-sentences', strand: 'grammar', title: 'Complex Sentences',
      description: 'Combining an independent clause with one or more dependent clauses to show relationships between ideas.',
      sample_passage: 'Although the rain had stopped, the streets stayed empty, because everyone remembered last year\'s flood.',
      order_index: 7,
      question: 'Which part of this sentence could stand alone as a complete sentence, and which parts depend on it?',
      misconception_triggers: ['complex means using big words', 'a long sentence is automatically complex', 'compound and complex are the same thing'],
    },
    {
      id: 'grammar-punctuation-effect', strand: 'grammar', title: 'Punctuation for Effect',
      description: 'Using colons, semicolons, and dashes deliberately to control pacing and emphasis.',
      sample_passage: 'She had one rule — never look back — and she had broken it exactly once.',
      order_index: 8,
      question: 'What does the pair of dashes do to the phrase "never look back" that a comma would not?',
      misconception_triggers: ['dashes and commas do the same job', 'semicolons join any two sentences', 'colons are only for lists'],
    },
    {
      id: 'grammar-cohesive-devices', strand: 'grammar', title: 'Cohesive Devices',
      description: 'Using connectives, pronouns, and reference words to link ideas across sentences and paragraphs.',
      sample_passage: 'The experiment failed twice. Consequently, the team changed their method. This new approach, however, raised a different problem.',
      order_index: 9,
      question: 'What job is the word "consequently" doing between the first two sentences?',
      misconception_triggers: ['cohesion just means using and', 'connectives only join within one sentence', 'this word only refers to the last sentence'],
    },
    {
      id: 'vocabulary-connotations', strand: 'vocabulary', title: 'Connotations',
      description: 'Recognizing the emotional associations of a word beyond its dictionary definition.',
      sample_passage: 'The reporter could have called him "frugal" or "stingy." She chose "stingy."',
      order_index: 10,
      question: 'Both words describe someone careful with money — so why does the choice between them matter?',
      misconception_triggers: ['the words mean exactly the same thing', 'connotation is the same as denotation', 'word choice does not affect meaning'],
    },
    {
      id: 'vocabulary-etymology', strand: 'vocabulary', title: 'Etymology',
      description: 'Using word origins and roots to work out or deepen the meaning of unfamiliar vocabulary.',
      sample_passage: 'The word "spectator" comes from the Latin "spectare," meaning "to watch." A "spectacle" is something worth watching.',
      order_index: 11,
      question: 'Given that root, what would you guess the word "spectacular" has to do with watching?',
      misconception_triggers: ['word origin does not affect current meaning', 'etymology is just history trivia', 'roots only matter for scientific words'],
    },
    {
      id: 'vocabulary-academic-diction', strand: 'vocabulary', title: 'Academic Diction',
      description: 'Choosing precise Tier-2 and Tier-3 words appropriate for formal academic writing.',
      sample_passage: '"The data shows the plan didn\'t work" versus "The data indicates the plan was ineffective."',
      order_index: 12,
      question: 'What changes in precision or formality when "didn\'t work" becomes "was ineffective"?',
      misconception_triggers: ['academic words just mean fancier words', 'simple words are always wrong in essays', 'diction only matters in speeches'],
    },
  ],
};
