/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'primary': '#2a49df',
        'primary-container': '#4965f9',
        'primary-fixed': '#dee0ff',
        'primary-fixed-dim': '#bac3ff',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#00105b',
        'secondary': '#006c49',
        'secondary-container': '#6cf8bb',
        'secondary-fixed': '#6ffbbe',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#00714d',
        'tertiary': '#825100',
        'tertiary-container': '#a36700',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#2a1700',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#444655',
        'outline': '#757687',
        'outline-variant': '#c5c5d8',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f8f9ff',
      },
      maxWidth: {
        'container-max': '72rem',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
    },
  },
  plugins: [],
};